blank_issues_enabled: false
contact_links:
  - name: ":speech_balloon: GitHub Community Support"
    url: https://github.com/CertifaiAI/CertifAI-Knowledge-Base/wiki
    about: Please ask and answer questions here.